# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\研究生\研一\空间分析软件\代码\UI测试\UI\uis\columns\right_column.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RightColumn(object):
    def setupUi(self, RightColumn):
        RightColumn.setObjectName("RightColumn")
        RightColumn.resize(240, 600)
        self.main_pages_layout = QtWidgets.QVBoxLayout(RightColumn)
        self.main_pages_layout.setContentsMargins(5, 5, 5, 5)
        self.main_pages_layout.setSpacing(0)
        self.main_pages_layout.setObjectName("main_pages_layout")
        self.widget = QtWidgets.QWidget(RightColumn)
        self.widget.setObjectName("widget")
        self.main_pages_layout.addWidget(self.widget)

        self.retranslateUi(RightColumn)
        QtCore.QMetaObject.connectSlotsByName(RightColumn)

    def retranslateUi(self, RightColumn):
        _translate = QtCore.QCoreApplication.translate
        RightColumn.setWindowTitle(_translate("RightColumn", "Form"))
